### ISSUE TITLE
thorlabs-ell18: releases busy before position is done moving

### ISSUE THREAD

**Issue by ddkohler** [yaq-project/yaqd-thorlabs#3]
in 2D scans, daemon reports not busy early. This was observed in carriage returns of 2D acquisitions, where the first reported point strongly deviated from the set position.

**Comment by ksunden** [comment]
This is an instance of a common yaq problem whereby we have a queue of responses, some of which set busy to "False", which gets processed after a move has been initiated, such that a daemon incorrectly then says it is not busy while it is in motion.

The fix is something along the lines of:

- set a flag to hold adding read operations which could set busy to false
- clear out existing messages, using the same flag to ensure that busy remains true
- initiate motion (technically can be done prior to clearing out the queue)
- once the message queue is clear, ensure busy is true and release the flag/lock, which then lets busy go false when it is true

**Comment by ksunden** [comment]
closed by #9
